### ISSUE TITLE
Consider switching to the syntax highlighting library in `egui_extras`

### ISSUE THREAD

**Issue by emilk** [lampsitter/egui_commonmark#13]
I recently moved the syntax highlighting code I had in `egui_demo_lib` to `egui_extras`: https://github.com/emilk/egui/pull/3333

Importantly, it has a simple fallback that works even without the `syntect` crate (which has a tendency to bloat .wasm files quite a bit).

`egui_extras::syntax_highlighing` does not yet support everything that `egui_commonmark` offers, in particular it doesn't yet have `add_syntax_from_folder`, `add_syntax_from_str`, `add_syntax_themes_from_folder`, and `add_syntax_theme_from_bytes`.

**Comment by lampsitter** [comment]
While being able to have fallback highlighting is nice, I don't like losing the more granular control I'm able to have by using syntect directly.

E.g: Using syntects custom cursor colour and selection colour.

**Comment by emilk** [comment]
Of course, I propose we expose that in `egui_extras::syntax_highlighing` somehow, in an interface that is agnostic to the implementation (syntect or fallback).

**Comment by lampsitter** [comment]
I don't think that it is possible to add a backend agnostic highlighter. `add_syntax_themes_from_folder` uses .tmTheme files, which are extremely syntect/sublime specific. I think it would be better to have a separate "feature" for using a crate with more primitive highlighting directly. Unfortunately I can't find such a crate...

**Comment by emilk** [comment]
I would suggest that `add_syntax_themes_from_folder` would only exist when compiling with the syntect backend, or that it would return an error when the feature was off.

**Comment by lampsitter** [comment]
I have added egui_extras as a fallback when the syntax_highlighting feature is disabled, which should have the desired effect.
