### ISSUE TITLE
Newline after list

### ISSUE THREAD

**Issue by vincev** [lampsitter/egui_commonmark#2]
I have noticed that when `egui_commonmark` renders the following md:

```
This is the list:
* The first item
	* First A nested item
	* First Another nested item
* The second item
	* Second nested item
		* A nested nested item
		* A nested nested another item
	* Second another nested
* The third item

A numbered list:

1. One
	1. One nested
	2. Two nested
		1. One one nested
		2. Two two nested
2. Two
3. Three

This is after the list.
```
we get this rendering with the line after the list attached to the list:

<img width="339" alt="Screenshot 2022-10-07 at 10 35 30" src="https://user-images.githubusercontent.com/10183380/194510485-4e8fe16f-ee29-4c05-a267-41ad9b71842b.png">

to make it behave like github would be nice to render it like this:

<img width="343" alt="Screenshot 2022-10-07 at 10 36 44" src="https://user-images.githubusercontent.com/10183380/194510788-006be68d-c304-4616-bb38-9190b026c8db.png">

The change is small one more newline:

```rs
            pulldown_cmark::Tag::List(_) => {
                self.indentation -= 1;
                if self.indentation == -1 {
                    newline(ui);
                    newline(ui);
                }
            }
```

I understand this may be subjective though, what do you think?

**Comment by lampsitter** [comment]
I agree. The suggested change won't work in all scenarios, though (before headings). I need to do some changes to how newlines are inserted, to fix this properly.
