### ISSUE TITLE
Copy button doesn't work on Safari

### ISSUE THREAD

**Issue by abey79** [lampsitter/egui_commonmark#21]
Safari has a marked tendency of rejecting copy operations that it can't link to user action. For this reason, most copy operations used to fail on Safari with egui/wasm. This was recently fixed in egui 0.24 (https://github.com/emilk/egui/pull/3513), and now copying from code blocks works when selecting text and copy. However it still fails when using the copy button.

Here is a dev build of Rerun based on egui 0.24 where select-and-copy works on Safari, but not the copy button:

https://demo.rerun.io/pr/4111/examples/structure_from_motion/

One must scroll down the `description` view to reach a code block:

<img width="1445" alt="image" src="https://github.com/lampsitter/egui_commonmark/assets/49431240/cf135e89-0f8b-4ee0-b62c-346bb7b34cf0">

Clicking the "Copy" button fails with this error:

<img width="1445" alt="image" src="https://github.com/lampsitter/egui_commonmark/assets/49431240/f024a5c1-e592-4544-8822-d98ec31e2b4a">

For reference, this is another dev build that is based on egui 0.23 and where all forms of copying fail:

https://demo.rerun.io/pr/4324/examples/structure_from_motion/

**Comment by emilk** [comment]
The problem is in `eframe`: https://github.com/emilk/egui/pull/3513 fixed copy/cut when using keyboard shortcuts, but not when using the mouse buttons. I can make a patch release to fix it.

**Comment by abey79** [comment]
Fixed by https://github.com/emilk/egui/pull/3621
