### ISSUE TITLE
Is there some sort of a solution to disparity in image paths between WASM and native targets?

### ISSUE THREAD

**Issue by JohnDowson** [lampsitter/egui_commonmark#23]

**Comment by lampsitter** [comment]
I'm not familiar with wasm and egui_extras default image loaders so I don't know. But if I were to guess, there's probably no easy way around having to use `#[cfg(target_arch = "wasm32")]`

**Comment by JohnDowson** [comment]
Well my problem is taht there isn't really a place to put that annotation.
I'm rendering a TUTORIAL.md from the repo, that has image links pointing into the repo. I can make sure that on web deployment same images are available at the same relative URI, but this crate seemingly can't handle chema-less URIs as URLs?

**Comment by JohnDowson** [comment]
Therre is a [`explicit_image_uri_scheme`](https://docs.rs/egui_commonmark/latest/egui_commonmark/struct.CommonMarkViewer.html#method.explicit_image_uri_scheme) method that is named like it could help, but it doesn not take an override schema to be used for schema-less links instead of `file://`.

**Comment by lampsitter** [comment]
Adding an override option for the default implied schema is something I can do.
