### ISSUE TITLE
Styling in markdown tables is broken

### ISSUE THREAD

**Issue by Wumpf** [lampsitter/egui_commonmark#34]
Here's an unstyled table, it's fine:
![image](https://github.com/rerun-io/rerun/assets/2910679/b1489ed0-8087-4189-9eaa-52d6b84ea3c9)

And then adding a bit of bold and italics...:
![image](https://github.com/rerun-io/rerun/assets/2910679/385e2aa7-8442-419c-9a25-c71c88f99a2f)

Screenshots are from https://github.com/rerun-io/rerun which uses this crate to render markdowns with egui :). Rerun Sided tracking issue https://github.com/rerun-io/rerun/issues/5588

**Comment by Wumpf** [comment]
Ah this might actually be duplicate of 
*  #33

so few tickets and I still missed it 😅 
Keeping it open until confirmed

**Comment by lampsitter** [comment]
I'm unable to reproduce this.  Can you try again with master now that #33 is fixed? If it does not solve it, please provide the original markdown.

**Comment by Wumpf** [comment]
will do on Monday, thx!

**Comment by Wumpf** [comment]
confirmed this fixes it!
