### ISSUE TITLE
Wrong vertical spacing around bullet lists

### ISSUE THREAD

**Issue by emilk** [lampsitter/egui_commonmark#47]
```md
Stuff:
* foo
* bar

That's it.
```

=>

<img width="87" alt="Screenshot 2024-04-08 at 16 48 55" src="https://github.com/lampsitter/egui_commonmark/assets/1148717/66ddbbe5-d8be-417f-b487-2816a64cf633">

Notice two problems:
* Extra vspace above the list
* Missing vspace below the list

**Comment by lampsitter** [comment]
Unable to reproduce on master
