### ISSUE TITLE
two or more spaces, then type return

### ISSUE THREAD

**Issue by sbechet** [lampsitter/egui_commonmark#59]
On [John Gruber, Markdown Syntax Documentation](https://daringfireball.net/projects/markdown/syntax)

We can read : "When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return."

It seems it's not working on egui_commonmark, is this intended?

Thank you for your work.

**Comment by lampsitter** [comment]
It does work with two spaces after `first line  `. Is there something else that you have in mind? 
![Screenshot_20240722_095416](https://github.com/user-attachments/assets/6e8e1343-9fab-4c06-85eb-37228c7e3580)

The reference spec works the same way:
https://spec.commonmark.org/dingus/?text=first%20line%20%20%0Asecond%20line%0A%0Atext%20with%20a%20%5C%0Abreak%0A%0Atext%20with%20a%20large%0A%0Aseparator

**Comment by sbechet** [comment]
ooops sorry, i test it on a bad way.
