### ISSUE TITLE
CommonMarkViewer doesn't render newline properly

### ISSUE THREAD

**Issue by chianti-ga** [lampsitter/egui_commonmark#61]
A new line in a string from a multiline text edit doesn't render properly, the return only occurs when a blank newline is added.

Exemple:
![image](https://github.com/user-attachments/assets/fe530fa0-0006-431d-afa8-1cef75300071)

**Comment by lampsitter** [comment]
That is intended. See: 

https://spec.commonmark.org/dingus/?text=a%20line%0Aa%20new%20line%0A%0Aanother%20line%20%0A%0A

If you want to break them you can instead do
```markdown
a line \
a new line
```

**Comment by chianti-ga** [comment]
thanks for the info
