### ISSUE TITLE
Show a tooltip containing the url of a link when hoverring it 

### ISSUE THREAD

**Issue by chianti-ga** [lampsitter/egui_commonmark#68]
It would be useful to display a tooltip containing the URL when a user hovers over a link.
This would enhance the user experience and security by providing more context on where a link points to without needing to click on it.

**Comment by chianti-ga** [comment]
> It's an annoying egui default. It can be enabled with:
> 
> ```rust
> ui.style_mut().url_in_tooltip = true;
> ```
> 
> It's written in the [docs](https://docs.rs/egui_commonmark/0.18.0/egui_commonmark/)

Thank you for pointing that out! I’ll enable `ui.style_mut().url_in_tooltip as suggested`. I hadn’t realized this was already documented.

**Comment by lampsitter** [comment]
I'll add it to the README too so that it is easier to discover.
